theme: jekyll-theme-minimal
title: Cornell Node of the NSF-Census Research Network - Reports
author:
  name: Lars Vilhuber
  twitter: larsvil
twitter_username: larsvil
github_username: larsvilhuber
logo: assets/cornell_logo_simple_black.svg
description: Description and List of Outcomes of the Cornell node of the NSF-Census Research Network
show_sites: true
show_downloads: false
